DOSKEY ls=dir
DOSKEY c=cls
DOSKEY clear=cls
DOSKEY nrw=npm run webpack
DOSKEY nrs=npm run start
DOSKEY finder=explorer .
DOSKEY n=start cmd.exe
DOSKEY sbt="D:\ProgramFiles\Sublime Text 3\sublime_text.exe" $*
DOSKEY pwd=cd
DOSKEY pbcopy=clip
DOSKEY vi="D:\ProgramFiles\Vim\vim80\gvim.exe" $*
DOSKEY gp="perl" D:\Developer\perlUtils\gp.pl $*
